version: 2.1
jobs:
  build_and_push:
    docker:
      - image: cimg/node:20.3.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build --build-arg NPM_TOKEN=$NPM_TOKEN -t prathvipp/todo-app:$CIRCLE_BUILD_NUM .
      - run:
          name: Docker Login
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Push Docker Image
          command: docker push prathvipp/todo-app:$CIRCLE_BUILD_NUM
workflows:
  version: 2
  build_and_push:
    jobs:
      - build_and_push
contexts:
  - docker-context